name: 🐛 Bug Report
description: Report a bug to help us improve PatchTrack
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce this behavior.
      placeholder: |
        1. Run '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: e.g. Python 3.14, MkDocs 1.5, OS: Ubuntu 22.04
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: If applicable, add screenshots or paste error logs here.